# Disable certgen
certgen:
  job:
    annotations:
      config.kubernetes.io/local-config: "true"
  rbac:
    annotations:
      config.kubernetes.io/local-config: "true"

topologyInjector:
  enabled: true
  annotations:
    cert-manager.io/inject-ca-from: envoy-gateway-system/envoy-gateway-ca

global:
  images:
    envoyGateway:
      pullPolicy: Always

deployment:
  envoyGateway:
    # Envoy Gateway がデフォルトで生成する xDS Cluster の DNS ポリシーが V4_PREFERRED になっていて IPv6 Only からの接続性に問題がある
    #TODO: Envoy Gateway に Issue を立ててトラックする
    image:
      repository: ghcr.io/tosuke-lab/envoy-gateway
      tag: v1.5.4-ipv6 # See: tosuke-lab/gateway#1
    imagePullPolicy: Always

config:
  envoyGateway:
    telemetry:
      metrics:
        sinks:
          - type: OpenTelemetry
            openTelemetry:
              protocol: grpc
              host: otlp.telemetry.svc.cluster.local
              port: 4317
