apiVersion: v1
kind: ServiceAccount
metadata:
  name: hmac-secret-manager
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: hmac-secret-manager
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create"]
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["envoy-oidc-hmac"]
    verbs:
      - get
      - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: hmac-secret-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: hmac-secret-manager
subjects:
  - kind: ServiceAccount
    name: hmac-secret-manager
---
apiVersion: batch/v1
kind: Job
metadata:
  name: hmac-secret-init
  annotations:
    argocd.argoproj.io/hook: PostSync
spec:
  completions: 1
  parallelism: 1
  backoffLimit: 0
  ttlSecondsAfterFinished: 300
  template:
    metadata:
      labels:
        app.kubernetes.io/name: hmac-secret-init
    spec:
      serviceAccountName: hmac-secret-manager
      restartPolicy: Never
      containers:
        - name: hmac-secret-init
          image: alpine/kubectl:1.34.1
          imagePullPolicy: IfNotPresent
          command: ["/bin/sh"]
          args:
            - -c
            - >
              kubectl create secret generic envoy-oidc-hmac
              --from-file=hmac-secret=<(head -c 32 /dev/urandom)
              || true
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: hmac-secret-rotation
spec:
  schedule: "0 2 1 */3 *"
  timeZone: Asia/Tokyo
  startingDeadlineSeconds: 3600
  jobTemplate:
    metadata:
      labels:
        app.kubernetes.io/name: hmac-secret-rotation
    spec:
      completions: 1
      parallelism: 1
      backoffLimit: 0
      template:
        metadata:
          labels:
            app.kubernetes.io/name: hmac-secret-rotation
        spec:
          serviceAccountName: hmac-secret-manager
          restartPolicy: Never
          containers:
            - name: hmac-secret-rotation
              image: alpine/kubectl:1.34.1
              imagePullPolicy: IfNotPresent
              command: ["/bin/sh"]
              args:
                - -c
                - >
                  kubectl create secret generic envoy-oidc-hmac 
                  --from-file=hmac-secret=<(head -c 32 /dev/urandom)
                  --dry-run=client --output=yaml
                  | kubectl replace -f -
