apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-system
  source:
    repoURL: https://github.com/ictsc/ictsc-k8s-infra
    targetRevision: main
    path: manifests/argocd-apps
    directory:
      include: dev.generated.yaml
  syncPolicy:
    automated:
      enabled: true
    syncOptions:
      - ServerSideApply=true
