apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-param
  annotations:
    config.kubernetes.io/local-config: "true"
data:
  k8s-domain: k8s-dev
  cluster-name: ictsc-dev
  vault-id: "113702555287"
  thanos-prefix: thanos/dev
  loki-prefix: loki-dev
