resources:
  - ../base
  - cluster-param.yaml

components:
  - ../components

images:
  - name: opentelemetry-collector-k8s
    newName: ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-k8s
    newTag: 0.140.1
  - name: opentelemetry-target-allocator
    newName: ghcr.io/open-telemetry/opentelemetry-operator/target-allocator
    newTag: 0.139.0
  - name: prometheus-operator
    newName: quay.io/prometheus-operator/prometheus-operator
    newTag: v0.87.0
  - name: prometheus
    newName: quay.io/prometheus/prometheus
    newTag: v3.7.3
  - name: thanos
    newName: quay.io/thanos/thanos
    newTag: v0.40.1
  - name: loki
    newName: docker.io/grafana/loki
    newTag: 3.6.2
  - name: k8s-sidecar
    newName: docker.io/kiwigrid/k8s-sidecar
    newTag: 2.1.4
  - name: otel-autoinstrumentation-python
    newName: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-python
    newTag: 0.59b0
