apiVersion: cilium.io/v2
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: cloudnative-pg-instance
spec:
  endpointSelector:
    matchExpressions:
      - key: cnpg.io/cluster
        operator: Exists
      - key: cnpg.io/podRole
        operator: In
        values:
          - instance
  ingress:
    - fromEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: cnpg-system
            app.kubernetes.io/name: cloudnative-pg
        - matchExpressions:
            - key: cnpg.io/cluster
              operator: Exists
      toPorts:
        - ports:
            - port: status
              protocol: TCP
    - fromEndpoints:
        - matchExpressions:
            - key: cnpg.io/cluster
              operator: Exists
      toPorts:
        - ports:
            - port: postgresql
              protocol: TCP
    - fromEntities: [cluster]
      toPorts:
        - ports:
            - port: metrics
              protocol: TCP
          rules:
            http:
              - method: GET
                path: /metrics
