apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: envoy-gateway
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: envoy-gateway-system
  source:
    repoURL: https://github.com/ictsc/ictsc-k8s-infra
    targetRevision: main
    path: manifests/envoy-gateway
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
