apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gateway
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: gateway
  source:
    repoURL: https://github.com/ictsc/ictsc-k8s-infra
    targetRevision: main
    path: manifests/gateway
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
