apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-param
  annotations:
    config.kubernetes.io/local-config: "true"
data:
  k8s-domain: k8s-prod
  cluster-name: ictsc-prod
  vault-id: "113702773889"
  thanos-prefix: thanos/prod
  loki-prefix: loki-prod
