apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k0s-cluster-view
  labels:
    rbac.authorization.k8s.io/aggregate-to-cluster-view: "true"
rules:
  - apiGroups: ["autopilot.k0sproject.io"]
    resources:
      - controlnodes
      - plans
      - updateconfigs
    verbs: ["get", "list", "watch"]
  - apiGroups: ["etcd.k0sproject.io"]
    resources: ["etcdmembers"]
    verbs: ["get", "list", "watch"]
