apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-param
  annotations:
    config.kubernetes.io/local-config: "true"
data:
  web-gateway-ips: 2001:e42:407:1047:1::80,64:ff9b::163.43.66.205
  web-gateway-replicas: 2
  k8s-domain: k8s-prod
  vault-id: "113702773889"
  auth-proxy-client-id: or4pllyrzelrqeb3og2psunvm
