apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  source:
    repoURL: https://github.com/ictsc/ictsc-k8s-infra
    targetRevision: main
    path: manifests/cert-manager
    directory:
      include: dev.generated.yaml
  syncPolicy:
    automated:
      enabled: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
