namespace: argo-system

resources:
  - ../base
  - scoreserver-app.yaml

patches:
  - target:
      kind: Application
      labelSelector: app-type=infra
    patch: |-
      - op: add
        path: /spec/source/directory
        value:
          include: "{crds,dev}.generated.yaml"
