namespace: kube-system

resources:
  - rbac.yaml
  - deployment.yaml
  - service.yaml
  - network-policy.yaml

configMapGenerator:
  - name: coredns
    files:
      - Corefile
    options:
      disableNameSuffixHash: true
