---
- name: Install nftables
  ansible.builtin.package:
    name: nftables
    state: present

- name: Deploy nftables configuration
  ansible.builtin.template:
    src: nftables.conf.j2
    dest: /etc/nftables.conf
    mode: '0644'
    owner: root
    group: root
    validate: nft -c -f %s
  notify: Reload nftables

- name: Enable and start nftables service
  ansible.builtin.systemd:
    name: nftables
    enabled: yes
    state: started
