resources:
  - ../base
  - cluster-param.yaml

components:
  - ../components

images:
  - name: busybox
    newName: busybox
    newTag: "1.37.0"
  - name: valkey/valkey
    newName: valkey/valkey
    newTag: 9.0.0-trixie
  - name: otel/opentelemetry-collector-contrib
    newName: otel/opentelemetry-collector-contrib
    newTag: 0.141.0
  - name: haproxy
    newName: haproxy
    newTag: "3.3.0"
