apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: argocd-metrics
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: argo-cd
  jobLabel: app.kubernetes.io/name
  podMetricsEndpoints:
    - port: metrics
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: argocd-metrics
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/instance: argo-cd
  ingress:
    - fromEntities: [cluster]
      toPorts:
        - ports:
            - port: metrics
              protocol: TCP
          rules:
            http:
              - method: GET
                path: /metrics
