apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: sakuracloud-secret
spec:
  provider: sakuracloud
  parameters:
    vaultID: $vaultID
    secrets: |
      - name: argocd-client-id
      - name: argocd-client-secret
  secretObjects:
    - secretName: oidc-secret
      labels:
        app.kubernetes.io/part-of: argocd
      type: Opaque
      data:
        - objectName: argocd-client-id
          key: clientID
        - objectName: argocd-client-secret
          key: clientSecret
---
# SecretProviderClass はマウントされないと効果がないので、Secret として固定するための Pod を用意する
apiVersion: v1
kind: ServiceAccount
metadata:
  name: secret-pin
  labels:
    app.kubernetes.io/name: secret-pin
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: secret-pin
  labels:
    app.kubernetes.io/name: secret-pin
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: secret-pin
  template:
    metadata:
      labels:
        app.kubernetes.io/name: secret-pin
    spec:
      serviceAccount: secret-pin
      containers:
        - name: pause
          image: registry.k8s.io/pause:3.10.1
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: secrets-store-inline
              mountPath: /mnt/secrets-store
              readOnly: true
          resources:
            limits:
              cpu: 2m
              memory: 10Mi
            requests:
              cpu: 1m
              memory: 1Mi
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: sakuracloud-secret
