apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
replacements:
  - source:
      kind: ConfigMap
      name: cluster-param
      fieldPath: data.web-gateway-ips
    targets:
      - select:
          kind: EnvoyProxy
          name: web
        options:
          create: true
        fieldPaths:
          - spec.provider.kubernetes.envoyService.annotations.[lbipam.cilium.io/ips]
  - source:
      kind: ConfigMap
      name: cluster-param
      fieldPath: data.web-gateway-replicas
    targets:
      - select:
          kind: EnvoyProxy
          name: web
        fieldPaths:
          - spec.provider.kubernetes.envoyDeployment.replicas
  - source:
      kind: ConfigMap
      name: cluster-param
      fieldPath: data.k8s-domain
    targets:
      - select:
          kind: Gateway
          name: web
        options:
          delimiter: "."
          index: 1
        fieldPaths:
          - spec.listeners.[name=argocd-https].hostname
      - select:
          kind: Gateway
          name: web-with-auth
        options:
          delimiter: "."
          index: 1
        fieldPaths:
          - spec.listeners.[name=login-https].hostname
          - spec.listeners.[name=hubble-https].hostname
      - select:
          kind: SecurityPolicy
          name: web-oidc-auth
        options:
          delimiter: "."
          index: 1
        fieldPaths:
          - spec.oidc.redirectURL
      - select:
          kind: SecurityPolicy
          name: web-oidc-auth
        options:
          delimiter: "."
          index: 0
        fieldPaths:
          - spec.oidc.cookieDomain
      - select:
          kind: HTTPRoute
          name: login
        options:
          delimiter: "."
          index: 1
        fieldPaths:
          - spec.hostnames.0
  - source:
      kind: ConfigMap
      name: cluster-param
      fieldPath: data.vault-id
    targets:
      - select:
          kind: SecretProviderClass
        fieldPaths:
          - spec.parameters.vaultID
  - source:
      kind: ConfigMap
      name: cluster-param
      fieldPath: data.auth-proxy-client-id
    targets:
      - select:
          kind: SecurityPolicy
          name: web-oidc-auth
        fieldPaths:
          - spec.oidc.clientID
      - select:
          kind: SecretProviderClass
          name: sakuracloud-secret
        fieldPaths:
          - spec.secretObjects.[secretName=auth-proxy-client-secret].annotations.client-id
