apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
patches:
  # Helm Chart で CRD の生成を無効化できないので config.kubernetes.io/local-config を使って結果から消去する
  - target:
      kind: CustomResourceDefinition
      name: logicalvolumes.topolvm.io
    patch: |-
      - op: add
        path: /metadata/annotations/config.kubernetes.io~1local-config
        value: "true"
