# yaml-language-server: $schema=https://raw.githubusercontent.com/cilium/cilium/refs/tags/v1.19.0-pre.1/install/kubernetes/cilium/values.schema.json

k8sServiceHostRef:
  name: cilium-kubernetes-service-host
  key: host
k8sServicePort: 6443

kubeProxyReplacement: true
routingMode: native
l2NeighDiscovery:
  enabled: true
l2podAnnouncements:
  enabled: true
  interface: ens3
l2announcements:
  enabled: true

hostFirewall:
  enabled: true

ipv4:
  enabled: false
ipv6:
  enabled: true
ipv6NativeRoutingCIDR: 2000::/3
enableIPv6Masquerade: false

ipam:
  mode: kubernetes

loadBalancer:
  mode: dsr
  dsrDispatch: geneve
tunnelProtocol: geneve
underlayProtocol: ipv6

bandwidthManager:
  enabled: true

prometheus:
  enabled: true

operator:
  prometheus:
    enabled: true

gatewayAPI:
  enabled: true
  gatewayClass:
    create: "true"

hubble:
  metrics:
    enableOpenMetrics: true
    enabled:
      - dns
      - drop:sourceContext=workload;destinationContext=workload
      - tcp
      - flow
      - port-distribution
      - icmp
      - httpV2:exemplars=true;sourceContext=workload;destinationContext=workload
  tls:
    auto:
      method: cronJob
  relay:
    enabled: true
  ui:
    enabled: true
