# yaml-language-server: $schema=https://raw.githubusercontent.com/cilium/cilium/refs/tags/v1.19.0-pre.1/install/kubernetes/cilium/values.schema.json

k8sServiceHostRef:
  name: cilium-kubernetes-service-host
  key: host
k8sServicePort: 6443

kubeProxyReplacement: true
routingMode: native
l2NeighDiscovery:
  enabled: true
l2podAnnouncements:
  enabled: true
  interface: ens3
l2announcements:
  enabled: true

hostFirewall:
  enabled: true

ipv4:
  enabled: false
ipv6:
  enabled: true
ipv6NativeRoutingCIDR: 2000::/3
enableIPv6Masquerade: false

ipam:
  mode: kubernetes

gatewayAPI:
  enabled: true
  gatewayClass:
    create: "true"

hubble:
  tls:
    auto:
      method: cronJob
  relay:
    enabled: true
  ui:
    enabled: true
