namespace: gateway

resources:
  - namespace.yaml
  - issuer.yaml
  - secret.yaml
  - web-gateway.yaml
  - web-envoy-proxy.yaml
  - web-oidc-cookie-patch.yaml
  - web-network-policy.yaml
  - login-service.yaml
  - telemetry-mtls-policy.yaml
