apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: web-gateway
spec:
  controllerName: gateway.envoyproxy.io/gatewayclass-controller
  parametersRef:
    group: gateway.envoyproxy.io
    kind: EnvoyProxy
    name: web
    namespace: gateway
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: web
spec:
  ipFamily: IPv6
  mergeGateways: true
  provider:
    type: Kubernetes
    kubernetes:
      envoyDeployment:
        replicas: 0 # Replace to $web-gateway-replicas
        initContainers:
          - name: set-mtu
            image: busybox:1.36.1
            command:
              - sh
              - -c
              # 1500 - 70 (Geneve) - 12 (DSR Option)
              - ip link set dev eth0 mtu 1418
            securityContext:
              capabilities:
                add: ["NET_ADMIN"]
      envoyService:
        labels:
          k8s.ictsc.net/lb-ipv4: "true"
        annotations:
          service.cilium.io/forwarding-mode: dsr
        # Default Policy (Local) is incompatible with Cilium L2 LB
        externalTrafficPolicy: Cluster
  bootstrap:
    type: JSONPatch
    jsonPatches:
      # Enable Admin API Access
      - op: replace
        path: /admin/address/socket_address/address
        value: "::"
      - op: add
        path: /admin/address/socket_address/ipv4_compat
        value: true
  telemetry:
    accessLog:
      settings:
        - format:
            type: Text
            text: |
              [%START_TIME%] "%REQ(:METHOD)% %REQ(X-ENVOY-ORIGINAL-PATH?:PATH)% %PROTOCOL%" %RESPONSE_CODE% %RESPONSE_FLAGS% %BYTES_RECEIVED% %BYTES_SENT% %DURATION% "%REQ(X-FORWARDED-FOR)%" "%REQ(USER-AGENT)%" "%REQ(X-REQUEST-ID)%" "%REQ(:AUTHORITY)%" "%UPSTREAM_HOST%"
          sinks:
            - type: OpenTelemetry
              openTelemetry:
                backendRefs:
                  - name: otlp
                    namespace: telemetry
                    port: 4317
