apiVersion: v1
kind: ServiceAccount
metadata:
  name: loki-backend
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: loki-read
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: loki-write
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: loki-ruler
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: loki-ruler
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: loki-ruler
subjects:
  - kind: ServiceAccount
    name: loki-backend
