---
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart k0s controller
  ansible.builtin.systemd:
    name: k0scontroller
    state: restarted
  failed_when: false
