namespace: argo-system

resources:
  - ../base
  - scoreserver-app.yaml

patches:
  - target:
      kind: Application
      labelSelector: app-type=infra
    patch: |-
      - op: add
        path: /spec/source/directory
        value:
          include: "{crds,prod}.generated.yaml"
  - target:
      kind: Application
    patch: |-
      - op: add
        path: /spec/syncPolicy/automated/enabled
        value: true
      - op: add
        path: /spec/syncPolicy/automated/prune
        value: true
      - op: add
        path: /spec/syncPolicy/automated/selfHeal
        value: true
