apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: secret-pin
  name: secret-pin
  namespace: argo-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: secret-pin
  name: secret-pin
  namespace: argo-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: secret-pin
  template:
    metadata:
      labels:
        app.kubernetes.io/name: secret-pin
    spec:
      containers:
      - image: registry.k8s.io/pause:3.10.1
        imagePullPolicy: IfNotPresent
        name: pause
        resources:
          limits:
            cpu: 2m
            memory: 10Mi
          requests:
            cpu: 1m
            memory: 1Mi
        volumeMounts:
        - mountPath: /mnt/secrets-store
          name: secrets-store-inline
          readOnly: true
      serviceAccount: secret-pin
      volumes:
      - csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: sakuracloud-secret
        name: secrets-store-inline
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: argocd-server
  namespace: argo-system
spec:
  hostnames:
  - argocd.k8s-dev.ictsc.net
  parentRefs:
  - name: web
    namespace: gateway
  rules:
  - backendRefs:
    - group: ""
      kind: Service
      name: argo-cd-argocd-server
      port: 80
    matches:
    - path:
        type: PathPrefix
        value: /
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: sakuracloud-secret
  namespace: argo-system
spec:
  parameters:
    secrets: |
      - name: argocd-client-secret
    vaultID: "113702555287"
  provider: sakuracloud
  secretObjects:
  - data:
    - key: clientSecret
      objectName: argocd-client-secret
    labels:
      app.kubernetes.io/part-of: argocd
    secretName: oidc-secret
    type: Opaque
