# yaml-language-server: $schema=https://raw.githubusercontent.com/cert-manager/cert-manager/refs/tags/v1.19.1/deploy/charts/cert-manager/values.schema.json
config:
  apiVersion: controller.config.cert-manager.io/v1alpha1
  kind: ControllerConfiguration
  enableGatewayAPI: true
