apiVersion: v1
kind: Namespace
metadata:
  name: gateway
---
apiVersion: v1
data:
  default.conf: |
    server {
        listen 8080;
        listen [::]:8080;
        server_name localhost;

        location / {
            root /usr/share/nginx/html;
            index index.html index.htm;
        }

        error_page 500 502 503 504 /50x.html;
        location = /50x.html {
            root /usr/share/nginx/html;
        }
    }
kind: ConfigMap
metadata:
  name: login-nginx-config
  namespace: gateway
---
apiVersion: v1
kind: Service
metadata:
  name: login
  namespace: gateway
spec:
  ports:
  - name: http
    port: 80
    targetPort: http
  selector:
    app.kubernetes.io/name: login
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: login
  namespace: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: login
  template:
    metadata:
      labels:
        app.kubernetes.io/name: login
    spec:
      containers:
      - image: nginx:1.29.3
        name: nginx
        ports:
        - containerPort: 8080
          name: http
        resources:
          limits:
            cpu: 100m
            memory: 32Mi
          requests:
            cpu: 10m
            memory: 8Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
        volumeMounts:
        - mountPath: /etc/nginx/conf.d
          name: nginx-config
          readOnly: true
        - mountPath: /var/cache/nginx
          name: nginx-cache
        - mountPath: /var/run
          name: nginx-run
      securityContext:
        fsGroup: 10001
        runAsGroup: 10001
        runAsNonRoot: true
        runAsUser: 10001
        seccompProfile:
          type: RuntimeDefault
      volumes:
      - configMap:
          name: login-nginx-config
        name: nginx-config
      - emptyDir: {}
        name: nginx-cache
      - emptyDir: {}
        name: nginx-run
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: secret-pin
  namespace: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: secret-pin
  template:
    metadata:
      labels:
        app.kubernetes.io/name: secret-pin
    spec:
      containers:
      - image: registry.k8s.io/pause:3.10.1
        imagePullPolicy: IfNotPresent
        name: pause
        resources:
          limits:
            cpu: 2m
            memory: 10Mi
          requests:
            cpu: 1m
            memory: 1Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
        volumeMounts:
        - mountPath: /mnt/secrets-store
          name: secrets-store-inline
          readOnly: true
      securityContext:
        fsGroup: 10002
        runAsGroup: 10002
        runAsNonRoot: true
        runAsUser: 10002
        seccompProfile:
          type: RuntimeDefault
      volumes:
      - csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: sakuracloud-secret
        name: secrets-store-inline
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: telemetry-client-ca
  namespace: gateway
spec:
  commonName: telemetry
  duration: 87600h
  isCA: true
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: selfsigned-issuer
  privateKey:
    algorithm: RSA
    size: 2048
  secretName: telemetry-client-ca
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: telemetry-client-grafana-ictsc-net
  namespace: gateway
spec:
  commonName: grafana.ictsc.net
  dnsNames:
  - grafana.ictsc.net
  duration: 43800h
  issuerRef:
    kind: Issuer
    name: telemetry-client
  secretName: telemetry-client-grafana-ictsc-net
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt
  namespace: gateway
spec:
  acme:
    email: cert@icttoracon.net
    privateKeySecretRef:
      name: letsencrypt
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
    - http01:
        gatewayHTTPRoute:
          parentRefs:
          - kind: Gateway
            name: web
          podTemplate:
            metadata:
              labels:
                app.kubernetes.io/name: cm-acme-http-solver
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-staging
  namespace: gateway
spec:
  acme:
    email: cert@icttoracon.net
    privateKeySecretRef:
      name: letsencrypt-staging
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    solvers:
    - http01:
        gatewayHTTPRoute:
          parentRefs:
          - kind: Gateway
            name: web
          podTemplate:
            metadata:
              labels:
                app.kubernetes.io/name: cm-acme-http-solver
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: telemetry-client
  namespace: gateway
spec:
  ca:
    secretName: telemetry-client-ca
---
apiVersion: cilium.io/v2
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: gateway-web-proxy
  namespace: gateway
spec:
  description: Allow internet access to web Gateway Proxies in the gateway namespace
  endpointSelector:
    matchLabels:
      app.kubernetes.io/component: proxy
      gateway.envoyproxy.io/owning-gatewayclass: web-gateway
      k8s:io.kubernetes.pod.namespace: envoy-gateway-system
  ingress:
  - fromEntities:
    - all
    toPorts:
    - ports:
      - port: "10080"
        protocol: TCP
      - port: "10443"
        protocol: ANY
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: cert-manager-acme-http-solver
  namespace: gateway
spec:
  endpointSelector:
    matchLabels:
      acme.cert-manager.io/http01-solver: "true"
  ingress:
  - fromEndpoints:
    - matchLabels:
        app.kubernetes.io/component: proxy
        gateway.envoyproxy.io/owning-gatewayclass: web-gateway
        k8s:io.kubernetes.pod.namespace: envoy-gateway-system
    toPorts:
    - ports:
      - port: http
        protocol: TCP
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: login
  namespace: gateway
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: login
  ingress:
  - fromEndpoints:
    - matchLabels:
        app.kubernetes.io/component: proxy
        gateway.envoyproxy.io/owning-gatewayclass: web-gateway
        k8s:io.kubernetes.pod.namespace: envoy-gateway-system
    toPorts:
    - ports:
      - port: http
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: ClientTrafficPolicy
metadata:
  name: telemetry-mtls
  namespace: gateway
spec:
  targetRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: web
    sectionName: telemetry-https
  tls:
    clientValidation:
      caCertificateRefs:
      - kind: Secret
        name: telemetry-client-ca
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: ClientTrafficPolicy
metadata:
  name: web
  namespace: gateway
spec:
  http3: {}
  targetRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: web
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: web-with-auth
  tls:
    alpnProtocols:
    - h2
    - http/1.1
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: web
  namespace: gateway
spec:
  bootstrap:
    jsonPatches:
    - op: replace
      path: /admin/address/socket_address/address
      value: '::'
    - op: add
      path: /admin/address/socket_address/ipv4_compat
      value: true
    type: JSONPatch
  ipFamily: IPv6
  mergeGateways: true
  provider:
    kubernetes:
      envoyDeployment:
        initContainers:
        - command:
          - sh
          - -c
          - ip link set dev eth0 mtu 1418
          image: busybox:1.36.1
          name: set-mtu
          securityContext:
            capabilities:
              add:
              - NET_ADMIN
        replicas: 1
      envoyService:
        annotations:
          lbipam.cilium.io/ips: 2001:e42:407:103c:1::80,64:ff9b::163.43.176.221
          service.cilium.io/forwarding-mode: dsr
        externalTrafficPolicy: Cluster
        labels:
          k8s.ictsc.net/lb-ipv4: "true"
    type: Kubernetes
  telemetry:
    metrics:
      sinks:
      - openTelemetry:
          host: otlp.telemetry.svc.cluster.local
          port: 4317
        type: OpenTelemetry
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: web-oidc-auth
  namespace: gateway
spec:
  oidc:
    clientID: or4pllyrzelrqeb3og2psunvm
    clientSecret:
      name: auth-proxy-client-secret
    cookieDomain: k8s-dev.ictsc.net
    logoutPath: /oauth2/logout
    provider:
      backendSettings:
        retry:
          numRetries: 3
      issuer: https://dex.ictsc.net
    redirectURL: https://login.k8s-dev.ictsc.net/oauth2/callback
    scopes:
    - openid
    - offline_access
  targetRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: web-with-auth
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  annotations:
    cert-manager.io/issuer: letsencrypt
  name: web
  namespace: gateway
spec:
  gatewayClassName: web-gateway
  listeners:
  - allowedRoutes:
      namespaces:
        from: All
    name: http
    port: 80
    protocol: HTTP
  - allowedRoutes:
      namespaces:
        from: Selector
        selector:
          matchLabels:
            kubernetes.io/metadata.name: argo-system
    hostname: argocd.k8s-dev.ictsc.net
    name: argocd-https
    port: 443
    protocol: HTTPS
    tls:
      certificateRefs:
      - name: argocd-tls
      mode: Terminate
  - allowedRoutes:
      namespaces:
        from: Selector
        selector:
          matchLabels:
            kubernetes.io/metadata.name: telemetry
    hostname: telemetry.k8s-dev.ictsc.net
    name: telemetry-https
    port: 443
    protocol: HTTPS
    tls:
      certificateRefs:
      - name: web-tls
      mode: Terminate
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  annotations:
    cert-manager.io/issuer: letsencrypt
  name: web-with-auth
  namespace: gateway
spec:
  gatewayClassName: web-gateway
  listeners:
  - allowedRoutes:
      namespaces:
        from: Same
    hostname: login.k8s-dev.ictsc.net
    name: login-https
    port: 443
    protocol: HTTPS
    tls:
      certificateRefs:
      - name: web-auth-tls
      mode: Terminate
  - allowedRoutes:
      namespaces:
        from: Selector
        selector:
          matchLabels:
            kubernetes.io/metadata.name: kube-system
    hostname: hubble.k8s-dev.ictsc.net
    name: hubble-https
    port: 443
    protocol: HTTPS
    tls:
      certificateRefs:
      - name: web-auth-tls
      mode: Terminate
---
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: web-gateway
  namespace: gateway
spec:
  controllerName: gateway.envoyproxy.io/gatewayclass-controller
  parametersRef:
    group: gateway.envoyproxy.io
    kind: EnvoyProxy
    name: web
    namespace: gateway
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: login
  namespace: gateway
spec:
  hostnames:
  - login.k8s-dev.ictsc.net
  parentRefs:
  - name: web-with-auth
  rules:
  - backendRefs:
    - name: login
      port: 80
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: sakuracloud-secret
  namespace: gateway
spec:
  parameters:
    secrets: |
      - name: auth-proxy-client-secret
    vaultID: "113702555287"
  provider: sakuracloud
  secretObjects:
  - annotations:
      client-id: or4pllyrzelrqeb3og2psunvm
    data:
    - key: client-secret
      objectName: auth-proxy-client-secret
    secretName: auth-proxy-client-secret
    type: Opaque
