apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
spec:
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      include: dev.generated.yaml
    path: manifests/cert-manager
    repoURL: https://github.com/ictsc/ictsc-k8s-infra
    targetRevision: main
  syncPolicy:
    automated:
      enabled: true
      selfHeal: true
    syncOptions:
    - ServerSideApply=true
    - CreateNamespace=true
