apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      include: dev.generated.yaml
    path: manifests/cert-manager
    repoURL: https://github.com/ictsc/ictsc-k8s-infra
    targetRevision: main
  syncPolicy:
    automated:
      enabled: true
    syncOptions:
    - ServerSideApply=true
    - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: csi-secrets-store
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      include: dev.generated.yaml
    path: manifests/csi-secrets-store
    repoURL: https://github.com/ictsc/ictsc-k8s-infra
    targetRevision: main
  syncPolicy:
    automated:
      enabled: true
    syncOptions:
    - ServerSideApply=true
