apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    app-type: infra
  name: argocd-extra
  namespace: argo-system
spec:
  destination:
    namespace: argo-system
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      include: '{crds,dev}.generated.yaml'
    path: manifests/argocd-extra
    repoURL: https://github.com/ictsc/ictsc-k8s-infra
    targetRevision: main
  syncPolicy:
    automated:
      enabled: true
    syncOptions:
    - ServerSideApply=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    app-type: infra
  name: cert-manager
  namespace: argo-system
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      include: '{crds,dev}.generated.yaml'
    path: manifests/cert-manager
    repoURL: https://github.com/ictsc/ictsc-k8s-infra
    targetRevision: main
  syncPolicy:
    automated:
      enabled: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    app-type: infra
  name: cilium-extra
  namespace: argo-system
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      include: '{crds,dev}.generated.yaml'
    path: manifests/cilium-extra
    repoURL: https://github.com/ictsc/ictsc-k8s-infra
    targetRevision: main
  syncPolicy:
    automated:
      enabled: true
    syncOptions:
    - ServerSideApply=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    app-type: infra
  name: cloudnative-pg
  namespace: argo-system
spec:
  destination:
    namespace: cnpg-system
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      include: '{crds,dev}.generated.yaml'
    path: manifests/cloudnative-pg
    repoURL: https://github.com/ictsc/ictsc-k8s-infra
    targetRevision: main
  syncPolicy:
    automated:
      enabled: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    app-type: infra
  name: csi-secrets-store
  namespace: argo-system
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      include: '{crds,dev}.generated.yaml'
    path: manifests/csi-secrets-store
    repoURL: https://github.com/ictsc/ictsc-k8s-infra
    targetRevision: main
  syncPolicy:
    automated:
      enabled: true
    syncOptions:
    - ServerSideApply=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    app-type: infra
  name: envoy-gateway
  namespace: argo-system
spec:
  destination:
    namespace: envoy-gateway-system
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      include: '{crds,dev}.generated.yaml'
    path: manifests/envoy-gateway
    repoURL: https://github.com/ictsc/ictsc-k8s-infra
    targetRevision: main
  syncPolicy:
    automated:
      enabled: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    app-type: infra
  name: gateway
  namespace: argo-system
spec:
  destination:
    namespace: gateway
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      include: '{crds,dev}.generated.yaml'
    path: manifests/gateway
    repoURL: https://github.com/ictsc/ictsc-k8s-infra
    targetRevision: main
  syncPolicy:
    automated:
      enabled: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    app-type: infra
  name: scoreserver
  namespace: argo-system
spec:
  destination:
    namespace: scoreserver
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      include: '{crds,dev}.generated.yaml'
    path: manifests/scoreserver
    repoURL: https://github.com/ictsc/ictsc-k8s-infra
    targetRevision: main
  syncPolicy:
    automated:
      enabled: true
    syncOptions:
    - ServerSideApply=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: scoreserver-app
  namespace: argo-system
spec:
  destination:
    namespace: scoreserver
    server: https://kubernetes.default.svc
  project: default
  source:
    path: dev
    repoURL: https://github.com/ictsc/ictsc-regalia-release
    targetRevision: main
  syncPolicy:
    automated: {}
    syncOptions:
    - ServerSideApply=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    app-type: infra
  name: telemetry
  namespace: argo-system
spec:
  destination:
    namespace: telemetry
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      include: '{crds,dev}.generated.yaml'
    path: manifests/telemetry
    repoURL: https://github.com/ictsc/ictsc-k8s-infra
    targetRevision: main
  syncPolicy:
    automated:
      enabled: true
    syncOptions:
    - ServerSideApply=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    app-type: infra
  name: topolvm
  namespace: argo-system
spec:
  destination:
    namespace: topolvm-system
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      include: '{crds,dev}.generated.yaml'
    path: manifests/topolvm
    repoURL: https://github.com/ictsc/ictsc-k8s-infra
    targetRevision: main
  syncPolicy:
    automated:
      enabled: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
