resources:
  - ../base
  - cluster-param.yaml

components:
  - ../components

images:
  - name: busybox
    newName: busybox
    newTag: "1.35.0"
  - name: valkey/valkey
    newName: valkey/valkey
    newTag: 8.1.4-trixie
  - name: otel/opentelemetry-collector-contrib
    newName: otel/opentelemetry-collector-contrib
    newTag: 0.140.1
  - name: haproxy
    newName: haproxy
    newTag: "3.2.9"
