apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
replacements:
  - source:
      kind: ConfigMap
      name: cluster-param
      fieldPath: data.vault-id
    targets:
      - select:
          kind: SecretProviderClass
          name: discord-oauth-client
        fieldPaths:
          - spec.parameters.vaultID
