apiVersion: v1
kind: ServiceAccount
metadata:
  name: collector
  labels:
    app.kubernetes.io/component: collector
    app.kubernetes.io/name: opentelemetry-collector
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: host-collector
  labels:
    app.kubernetes.io/component: collector
    app.kubernetes.io/name: host-collector
---
# https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/v0.139.0/processor/k8sattributesprocessor#cluster-scoped-rbac
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: telemetry-collector:k8s-attributes-processor
rules:
  - apiGroups: [""]
    resources: ["pods", "namespaces", "nodes"]
    verbs: ["get", "watch", "list"]
  - apiGroups: ["apps"]
    resources: ["replicasets", "deployments", "statefulsets", "daemonsets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["extensions"]
    resources: ["replicasets"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: telemetry-collector:k8s-attributes-processor
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: telemetry-collector:k8s-attributes-processor
subjects:
  - kind: ServiceAccount
    name: collector
---
# https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/v0.139.0/receiver/k8sclusterreceiver#rbac
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: telemetry-collector:k8s-cluster-receiver
rules:
  - apiGroups: [""]
    resources:
      - events
      - namespaces
      - namespaces/status
      - nodes
      - nodes/spec
      - pods
      - pods/status
      - replicationcontrollers
      - replicationcontrollers/status
      - resourcequotas
      - services
    verbs: ["get", "watch", "list"]
  - apiGroups: ["apps"]
    resources: ["replicasets", "deployments", "statefulsets", "daemonsets"]
    verbs: ["get", "watch", "list"]
  - apiGroups: ["extensions"]
    resources: ["replicasets"]
    verbs: ["get", "watch", "list"]
  - apiGroups: ["batch"]
    resources: ["jobs", "cronjobs"]
    verbs: ["get", "watch", "list"]
  - apiGroups: ["autoscaling"]
    resources: ["horizontalpodautoscalers"]
    verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: telemetry-collector:k8s-cluster-receiver
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: telemetry-collector:k8s-cluster-receiver
subjects:
  - kind: ServiceAccount
    name: collector
---
# https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/v0.139.0/receiver/kubeletstatsreceiver#role-based-access-control
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: telemetry-collector:kubelet-stats-receiver
rules:
  - apiGroups: [""]
    resources: ["nodes/stats"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: telemetry-collector:kubelet-stats-receiver
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: telemetry-collector:kubelet-stats-receiver
subjects:
  - kind: ServiceAccount
    name: collector
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: telemetry-collector:kubernetes-metrics
rules:
  - apiGroups: [""]
    resources: ["nodes/metrics"]
    verbs: ["get"]
  - nonResourceURLs:
      - "/metrics"
      - "/metrics/slis"
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: telemetry-collector:kubernetes-metrics
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: telemetry-collector:kubernetes-metrics
subjects:
  - kind: ServiceAccount
    name: collector
---
# https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/v0.140.1/receiver/k8sobjectsreceiver#rbac
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: telemetry-collector:k8s-objects-receiver
rules:
  - apiGroups: [""]
    resources: ["events", "pods"]
    verbs: ["get", "watch", "list"]
  - apiGroups: ["events.k8s.io"]
    resources: ["events"]
    verbs: ["watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: telemetry-collector:k8s-objects-receiver
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: telemetry-collector:k8s-objects-receiver
subjects:
  - kind: ServiceAccount
    name: collector
---
# https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/v0.139.0/extension/k8sleaderelector
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: collector:leaderelection
  labels:
    app.kubernetes.io/component: collector
rules:
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "list", "watch", "create"]
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    resourceNames: ["collector-leader-election"]
    verbs: ["update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: collector:leaderelection
  labels:
    app.kubernetes.io/component: collector
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: collector:leaderelection
subjects:
  - kind: ServiceAccount
    name: collector
