labels:
  - pairs:
      app.kubernetes.io/part-of: opentelemetry-collector

configMapGenerator:
  - name: collector-config
    options:
      labels:
        app.kubernetes.io/component: collector
        app.kubernetes.io/name: collector-config
    files:
      - config.yaml=collector-config.yaml
  - name: host-collector-config
    options:
      labels:
        app.kubernetes.io/component: collector
        app.kubernetes.io/name: host-collector-config
    files:
      - config.yaml=host-collector-config.yaml

resources:
  - collector-rbac.yaml
  - collector.yaml
  - host-collector.yaml
  - target-allocator-rbac.yaml
  - target-allocator-deployment.yaml
  - target-allocator-service.yaml
