resources:
  - ../base
  - cluster-param.yaml
components:
  - ../components
patches:
  - target:
      group: gateway.networking.k8s.io
      kind: Gateway
      name: web
    patch: |-
      - op: add
        path: /spec/listeners/-
        value:
          name: admin-contest-https
          hostname: admin.contest.k8s-dev.ictsc.net
          protocol: HTTPS
          port: 443
          allowedRoutes:
            namespaces:
              from: Selector
              selector:
                matchLabels:
                  kubernetes.io/metadata.name: scoreserver
          tls:
            mode: Terminate
            certificateRefs:
              - name: web-tls
      - op: add
        path: /spec/listeners/-
        value:
          name: api-admin-contest-https
          hostname: api.admin.contest.k8s-dev.ictsc.net
          protocol: HTTPS
          port: 443
          allowedRoutes:
            namespaces:
              from: Selector
              selector:
                matchLabels:
                  kubernetes.io/metadata.name: scoreserver
          tls:
            mode: Terminate
            certificateRefs:
              - name: api-admin-contest-tls
      - op: add
        path: /spec/listeners/-
        value:
          name: contest-https
          hostname: contest.k8s-dev.ictsc.net
          protocol: HTTPS
          port: 443
          allowedRoutes:
            namespaces:
              from: Selector
              selector:
                matchLabels:
                  kubernetes.io/metadata.name: scoreserver
          tls:
            mode: Terminate
            certificateRefs:
              - name: web-tls
