name: Setup Tools
description: Install development tools using Aqua
runs:
  using: composite
  steps:
    - name: Install Aqua
      uses: aquaproj/aqua-installer@11dd79b4e498d471a9385aa9fb7f62bb5f52a73c # v4.0.4
      with:
        aqua_version: v2.55.1

    - name: Enable tenv auto install
      shell: bash
      run: |
        echo "TENV_AUTO_INSTALL=true" >> "$GITHUB_ENV"
