labels:
  - pairs:
      app-type: infra

resources:
  - cert-manager.yaml
  - cloudnative-pg.yaml
  - csi-secrets-store.yaml
  - envoy-gateway.yaml
  - gateway.yaml
  - argocd-extra.yaml
  - cilium-extra.yaml
  - topolvm.yaml
  - telemetry.yaml
  - scoreserver.yaml
