apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kube-apiserver
spec:
  jobLabel: component
  namespaceSelector:
    matchNames: [default]
  selector:
    matchLabels:
      component: apiserver
      provider: kubernetes
  endpoints:
    - path: /metrics
      port: https
      scheme: https
      tlsConfig:
        caFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        serverName: kubernetes
      bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      interval: 30s
    - path: /metrics/slis
      port: https
      scheme: https
      tlsConfig:
        caFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        serverName: kubernetes
      bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      interval: 5s
