labels:
  - pairs:
      app.kubernetes.io/part-of: prometheus

resources:
  - ./operator
  - prometheus.yaml
  - ./thanos
  - apiserver-monitor.yaml
  - k0s-metrics-monitor.yaml
  - coredns-monitor.yaml
