[project]
name = "ansible-environment"
version = "0.1.0"
description = "Ansible environment for ICTSC K8s infrastructure"
requires-python = ">=3.10"
dependencies = [
    "ansible>=10.0.0",
    "ansible-core>=2.17.0",
    "ansible-lint>=25.9.2",
]
