---
- name: Setup OpenTelemetry Collector
  hosts: all
  become: true
  roles:
    - otelcol
  vars:
    otelcol_sakuracloud_metrics_endpoint: >-
      {{ lookup('sakura_secret', 'sakuracloud-metrics-endpoint', vault_id=vault_id) }}
    otelcol_sakuracloud_metrics_token: >-
      {{ lookup('sakura_secret', 'sakuracloud-metrics-token', vault_id=vault_id) }}

- name: Setup NAT64 Box
  hosts: nat64box
  become: true
  roles:
    - nat64box
  vars:
    nat64box_proxy_ipv4_addrs: "{{ proxy_ipv4_addrs }}"

- name: Install k0s
  hosts: kubernetes
  become: true
  roles:
    - install_k0s

- name: Configure k0s on control plane
  hosts: cplane
  become: true
  roles:
    - cplane_firewall
    - k0s
  vars:
    cplane_firewall_cplane_ipv6_subnet: "{{ cplane_ipv6_cidr }}"
    cplane_firewall_worker_ipv6_subnet: "{{ worker_ipv6_cidr }}"
    k0s_cluster_name: "{{ k8s_cluster_name }}"
    k0s_k8s_api_host: "{{ k8s_api_host }}"
    k0s_k8s_api_ipv4: "{{ k8s_api_ipv4 }}"
    k0s_k8s_api_ipv6: "{{ k8s_api_ipv6 }}"
    k0s_k8s_pod_cidr: "{{ k8s_pod_cidr }}"
    k0s_k8s_service_cidr: "{{ k8s_service_cidr }}"
    k0s_k8s_lb_ipv4_addrs: "{{ k8s_lb_ipv4_addrs }}"
    k0s_k8s_lb_ipv6_subnet: "{{ k8s_lb_ipv6_cidr }}"
    k0s_nat64_prefix: "{{ nat64_prefix }}"

- name: Bootstrap first controller
  hosts: cplane:&bootstrap
  become: true
  roles:
    - bootstrap_controller
    - backup_k0s
  vars:
    backup_k0s_sakuracloud_s3_access_key_id: >-
      {{ lookup('sakura_secret', 'sakuracloud-s3-backup-access-key-id', vault_id=vault_id) }}
    backup_k0s_sakuracloud_s3_secret_access_key: >-
      {{ lookup('sakura_secret', 'sakuracloud-s3-backup-secret-access-key', vault_id=vault_id) }}

- name: Join additional controllers
  hosts: cplane:!bootstrap
  become: true
  roles:
    - join_controller

- name: Join workers
  hosts: worker
  become: true
  roles:
    - join_worker
