apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: discord-oauth-client
spec:
  provider: sakuracloud
  parameters:
    vaultID: $vault-id
    secrets: |
      - name: scoreserver-discord-client-id
      - name: scoreserver-discord-client-secret
  secretObjects:
    - secretName: discord-oauth-client
      type: Opaque
      data:
        - objectName: scoreserver-discord-client-id
          key: client-id
        - objectName: scoreserver-discord-client-secret
          key: client-secret
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: scoreserver-admin-oauth-client
spec:
  provider: sakuracloud
  parameters:
    vaultID: $vault-id
    secrets: |
      - name: scoreserver-admin-client-secret
  secretObjects:
    - secretName: scoreserver-admin-oauth-client
      type: Opaque
      data:
        - objectName: scoreserver-admin-client-secret
          key: client-secret
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: scoreserver-discord-bot
spec:
  provider: sakuracloud
  parameters:
    vaultID: $vault-id
    secrets: |
      - name: scoreserver-discord-bot-token
        path: bot-token
      - name: scoreserver-discord-bot-staff-password
        path: staff-password
  secretObjects:
    - secretName: scoreserver-discord-bot
      type: Opaque
      data:
        - objectName: bot-token
          key: bot-token
        - objectName: staff-password
          key: staff-password
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: scoreserver-sstate-credentials
spec:
  provider: sakuracloud
  parameters:
    vaultID: $vault-id
    secrets: |
      - name: sstate-password
        path: password
  secretObjects:
    - secretName: scoreserver-sstate-credentials
      type: Opaque
      data:
        - objectName: password
          key: password
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: scoreserver-master-deploy-key
spec:
  provider: sakuracloud
  parameters:
    vaultID: $vault-id
    secrets: |
      - name: ictsc-master-deploy-key
        path: deploy.key
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: secret-pin
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: secret-pin
  template:
    metadata:
      labels:
        app.kubernetes.io/name: secret-pin
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 10002
        runAsGroup: 10002
        fsGroup: 10002
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: pause
          image: registry.k8s.io/pause:3.10.1
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          volumeMounts:
            - mountPath: /run/scoreserver-admin-oauth-client
              name: scoreserver-admin-oauth-client
              readOnly: true
          resources:
            limits:
              cpu: 2m
              memory: 10Mi
            requests:
              cpu: 1m
              memory: 1Mi
      volumes:
        - name: scoreserver-admin-oauth-client
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: scoreserver-admin-oauth-client
