apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: discord-oauth-client
spec:
  provider: sakuracloud
  parameters:
    vaultID: $vault-id
    secrets: |
      - name: discord-oauth-client-id
      - name: discord-oauth-client-secret
  secretObjects:
    - secretName: discord-oauth-client
      type: Opaque
      data:
        - objectName: discord-oauth-client-id
          key: client-id
        - objectName: discord-oauth-client-secret
          key: client-secret
