global:
  networkPolicy:
    create: true

dex:
  enabled: false

configs:
  params:
    server.insecure: true
  cm:
    admin.enabled: false
    oidc.config: |
      name: OIDC
      issuer: https://dex.ictsc.net
      enablePKCEAuthentication: true
      clientID: $oidc.clientID
      clientSecret: $oidc-secret:clientSecret
      cliClientID: $oidc.cliClientID

server:
  service:
    # Insecure モードでサーバーを動作させるので、HTTPS ポートを gRPC 用に使う
    servicePortHttps: 81
    servicePortHttpsName: grpc
    servicePortHttpsAppProtocol: kubernetes.io/h2c
