port 26379
bind 0.0.0.0 ::
protected-mode no

sentinel resolve-hostnames yes
sentinel announce-hostnames yes

sentinel down-after-milliseconds valkey 5000
sentinel failover-timeout valkey 10000
sentinel parallel-syncs valkey 1
