# Valkey Configuration
port 6379
bind 0.0.0.0 ::
protected-mode no

# Persistence
dir /var/lib/valkey
appendonly yes
appendfsync everysec

# Replication
replica-read-only yes
replica-serve-stale-data yes

# Memory
maxmemory-policy allkeys-lru
