labels:
  - pairs:
      app.kubernetes.io/name: prometheus-operator
      app.kubernetes.io/component: controller

resources:
  - networkpolicy.yaml
  - monitor.yaml
  - controller-rbac.yaml
  - controller-deploy.yaml
