resources:
  - https://raw.githubusercontent.com/cloudnative-pg/cloudnative-pg/v1.27.1/config/crd/bases/postgresql.cnpg.io_backups.yaml
  - https://raw.githubusercontent.com/cloudnative-pg/cloudnative-pg/v1.27.1/config/crd/bases/postgresql.cnpg.io_clusterimagecatalogs.yaml
  - https://raw.githubusercontent.com/cloudnative-pg/cloudnative-pg/v1.27.1/config/crd/bases/postgresql.cnpg.io_clusters.yaml
  - https://raw.githubusercontent.com/cloudnative-pg/cloudnative-pg/v1.27.1/config/crd/bases/postgresql.cnpg.io_databases.yaml
  - https://raw.githubusercontent.com/cloudnative-pg/cloudnative-pg/v1.27.1/config/crd/bases/postgresql.cnpg.io_failoverquorums.yaml
  - https://raw.githubusercontent.com/cloudnative-pg/cloudnative-pg/v1.27.1/config/crd/bases/postgresql.cnpg.io_imagecatalogs.yaml
  - https://raw.githubusercontent.com/cloudnative-pg/cloudnative-pg/v1.27.1/config/crd/bases/postgresql.cnpg.io_poolers.yaml
  - https://raw.githubusercontent.com/cloudnative-pg/cloudnative-pg/v1.27.1/config/crd/bases/postgresql.cnpg.io_publications.yaml
  - https://raw.githubusercontent.com/cloudnative-pg/cloudnative-pg/v1.27.1/config/crd/bases/postgresql.cnpg.io_scheduledbackups.yaml
  - https://raw.githubusercontent.com/cloudnative-pg/cloudnative-pg/v1.27.1/config/crd/bases/postgresql.cnpg.io_subscriptions.yaml
