---
- name: Create k0s config directory
  ansible.builtin.file:
    path: "/etc/k0s"
    state: directory
    mode: "0755"
    owner: root
    group: root
- name: Deploy k0s configuration
  ansible.builtin.template:
    src: k0s.yaml.j2
    dest: "/etc/k0s/k0s.yaml"
    mode: "0644"
    owner: root
    group: root
  notify: Restart k0s controller
- name: Deploy authentication configuration
  ansible.builtin.template:
    src: auth-config.yaml.j2
    dest: "/etc/k0s/auth-config.yaml"
    mode: "0644"
    owner: root
    group: root

- name: Create k0s manifests directory for RBAC
  ansible.builtin.file:
    path: /var/lib/k0s/manifests/rbac
    state: directory
    mode: "0755"
    owner: root
    group: root
- name: Deploy RBAC manifest
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/../manifests/rbac/dev.generated.yaml"
    dest: /var/lib/k0s/manifests/rbac/rbac.yaml
    mode: "0644"
    owner: root
    group: root

- name: Create k0s manifests directory for Cilium
  ansible.builtin.file:
    path: /var/lib/k0s/manifests/cilium
    state: directory
    mode: "0755"
    owner: root
    group: root
- name: Deploy Cilium manifest
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/../manifests/cilium/dev.generated.yaml"
    dest: /var/lib/k0s/manifests/cilium/cilium.yaml
    mode: "0644"
    owner: root
    group: root
- name: Deploy cilium k8s host config map
  ansible.builtin.template:
    src: cilium-kubernetes-service-host-cm.yaml.j2
    dest: /var/lib/k0s/manifests/cilium/cilium-kubernetes-service-host-cm.yaml
    mode: "0644"
    owner: root
    group: root
- name: Deploy cilium ippool
  ansible.builtin.template:
    src: cilium-ippool.yaml.j2
    dest: /var/lib/k0s/manifests/cilium/cilium-ippool.yaml
    mode: "0644"
    owner: root
    group: root

- name: Create k0s manifests directory for CoreDNS
  ansible.builtin.file:
    path: /var/lib/k0s/manifests/coredns
    state: directory
    mode: "0755"
    owner: root
    group: root
- name: Deploy CoreDNS manifest
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/../manifests/coredns/dev.generated.yaml"
    dest: /var/lib/k0s/manifests/coredns/coredns.yaml
    mode: "0644"
    owner: root
    group: root

- name: Create k0s manifests directory for metrics
  ansible.builtin.file:
    path: /var/lib/k0s/manifests/metrics
    state: directory
    mode: "0755"
    owner: root
    group: root
- name: Deploy pushgateway network policy
  ansible.builtin.copy:
    src: k0s-pushgateway-network-policy.yaml
    dest: /var/lib/k0s/manifests/metrics/k0s-pushgateway-network-policy.yaml
    mode: "0644"
    owner: root
    group: root

- name: Create k0s manifests directory for ArgoCD
  ansible.builtin.file:
    path: /var/lib/k0s/manifests/argocd
    state: directory
    mode: "0755"
    owner: root
    group: root
- name: Deploy ArgoCD CRDs
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/../manifests/argocd-install/crds.generated.yaml"
    dest: /var/lib/k0s/manifests/argocd/10-argocd-crds.yaml
    mode: "0644"
    owner: root
    group: root
- name: Deploy ArgoCD manifest
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/../manifests/argocd-install/dev.generated.yaml"
    dest: /var/lib/k0s/manifests/argocd/20-argocd-install.yaml
    mode: "0644"
    owner: root
    group: root

- name: Ensure secret manifest directory exists
  ansible.builtin.file:
    path: /var/lib/k0s/manifests/secrets
    state: directory
    mode: "0700"
    owner: root
    group: root
- name: Deploy sakuracloud secret manifest
  ansible.builtin.template:
    src: sakuracloud-secret.yaml.j2
    dest: /var/lib/k0s/manifests/secrets/sakuracloud-secret.yaml
    mode: "0600"
    owner: root
    group: root
