storageClasses:
  - name: topolvm-provisioner
    storageClass:
      fsType: ext4
      allowVolumeExpansion: true

lvmd:
  deviceClasses:
    - name: ssd
      volume-group: ssd_vg
      default: true
      spare-gb: 10
  securityContext:
    privileged: true
    readOnlyRootFilesystem: true
  prometheus:
    podMonitor:
      enabled: true

node:
  kubeletWorkDirectory: /var/lib/k0s/kubelet
  podSecurityContext:
    seccompProfile:
      type: RuntimeDefault
  securityContext:
    privileged: true
    readOnlyRootFilesystem: true
  prometheus:
    podMonitor:
      enabled: true

controller:
  prometheus:
    podMonitor:
      enabled: true
