apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: topolvm-cluster-view
  labels:
    rbac.authorization.k8s.io/aggregate-to-cluster-view: "true"
rules:
  - apiGroups: ["topolvm.io"]
    resources: ["logicalvolumes"]
    verbs: ["get", "list", "watch"]
