name: autofix.ci

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  autofix:
    name: Autofix
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
      - uses: ./.github/actions/setup-tools
      - name: Format
        run: make fmt
      - name: Generate manifests
        run: make clean-manifests && make manifests
      - name: Autofix
        uses: autofix-ci/action@635ffb0c9798bd160680f18fd73371e355b85f27 # v1.3.2
