name: ci

on:
  pull_request:
  push:
    branches: [main]

permissions: {}

jobs:
  status-check:
    name: Status Check
    runs-on: ubuntu-latest
    if: failure()
    permissions: {}
    steps: [{ run: exit 1 }]
    needs:
      - lint

  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
      - uses: ./.github/actions/setup-tools
      - name: Lint
        run: make validate
