name: ci

on:
  pull_request:
  push:
    branches: [main]

permissions: {}

jobs:
  status-check:
    name: Status Check
    runs-on: ubuntu-latest
    if: failure()
    permissions: {}
    steps: [{ run: exit 1 }]
    needs:
      - lint

  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: ./.github/actions/setup-tools
      - name: Lint
        run: make validate
