name: On Pull Request

on:
  pull_request:

jobs:
  status-check:
    name: Status Check
    runs-on: ubuntu-latest
    if: failure()
    permissions: {}
    steps: [{ run: exit 1 }]
    needs:
      - lint

  lint:
    uses: ./.github/workflows/wf-lint.yaml
